version: '3.9'
services:
    backend:
        build: .
        ports:
            - 8000:3000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: rand_bg_api
            MYSQL_USER: root
            MYSQL_PASSWORD: dev
            MYSQL_ROOT_PASSWORD: dev
        volumes:
            - .dbdata:/var/lib/mysql