version: '3.9'
services:
    backend:
        build: .
        ports:
            - 8000:3000
        volumes:
            - .:/app
        depends_on:
            - db_rand_bg_api

    db_rand_bg_api:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: rand_bg_api
            MYSQL_USER: root
            MYSQL_PASSWORD: dev
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_TCP_PORT: 3307
            # SQL_INTERNAL_PORT: 3307
        volumes:
            - .dbdata:/var/lib/mysql
        ports:
            - 33077:3307